<?php

/**
 * Generated By GZeinNumerCodeGenerator
 * www.github.com/gzeinnumer
 * at 2022-07-11 06:14:21
 * zip name 20220628044734_barang_26oFbqeVjw.zip
 */

namespace App\Http\Controllers;

use App\Models\ProductsModel;
use Illuminate\Http\Request;
use stdClass;

use Yajra\DataTables\Facades\DataTables;
// composer require yajra/laravel-datatables-oracle:"~9.0"

class ProductsController extends Controller
{
    //list
    public function index()
    {
        $data = ProductsModel::all();
        $sent = [
            'data' => $data
        ];
        return view('products.index', $sent);
    }

    //add
    public function createShow()
    {
        return view('products.add');
    }

    public function createPerform(Request $r)
    {
        $data = new ProductsModel();
        $data->name = $r->name;
        $data->flag_active = $r->flag_active;
        $data->save();
        return redirect('/products')->with('sukses', 'Data successfully added');
    }

    //detail
    public function findShow($id)
    {
        return view('products.find');
    }

    //update
    public function updateShow($id)
    {
        return view('products.edit');
    }

    public function updatePerform(Request $r)
    {
        $data = ProductsModel::find($r->id);
        $data->update($r->all());
        return redirect('/products')->with('sukses', 'Data successfully updated');
    }

    //delete
    public function deleteShow($id)
    {
        $delete = ProductsModel::find($id);
        $sent = [
            'delete' => $delete
        ];
        return view('products.delete', $sent);
    }

    public function deletePerform(Request $r)
    {
        $data = ProductsModel::find($r->id);
        $data->delete();
        return redirect('/products')->with('sukses', 'Data berhasil deleted');
    }

    public function getDataById($id)
    {
        $find = ProductsModel::where(["id" => $id])->first();
        return json_encode($find);
    }

    //dataTables
    public function dataTables(Request $request)
    {
        if ($request->ajax()) {
            $data = $this->getData($request);

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($row) {
                    $actionBtn = "<td>" .
                        '    <a href="/products/find/' . $row->id . '" class="btn btn-info btn-sm ">Detail</a>' .
                        '    <a href="/products/update/' . $row->id . '" class="btn btn-warning btn-sm ">Edit</a>' .
                        '    <a href="/products/delete/' . $row->id . '" class="btn btn-danger btn-sm">Delete</a>' .
                        "</td>";
                    return $actionBtn;
                })
                ->rawColumns(['action'])
                ->make(true);
        }
    }

    public function getData(Request $request, $flag_active = "")
    {
        $date_start = $request->get("date_start");
        $date_end = $request->get("date_end");

        $data = ProductsModel::select('products.*');

        if ($date_start != "" && $date_end != "") {
            $data = $data->wherebetween("products.created_at", array($date_start . " 00:00:00", $date_end . " 23:59:59"));
        } else if ($date_start != "") {
            $data = $data->where("products.created_at", ">=", $date_start . " 00:00:00");
        } else if ($date_end != "") {
            $data = $data->where("products.created_at", "<=", $date_end . " 23:59:59");
        }

        $data = $data->get();;

        return $data;
    }

    public function getChart($date)
    {
        $colors = ["#206bc4", "#4299e1", "#4263eb", "#ae3ec9", "#d6336c", "#d63939", "#f76707", "#f59f00", "#74b816", "#2fb344", "#0ca678", "#17a2b8", "#1e293b", "#626976"];
        shuffle($colors);

        $values = ProductsModel::select('products.*')->get();

        $labels = [];
        $data1 = [];
        $color = [];
        $colorCount = 0;

        for ($i = 0; $i < count($values); $i++) {
            $labels[] = $values[$i]->id;
            $data1[] = ProductsModel::where(['id' => $values[$i]->id])->get()->count();
            $colorCount++;
            if ($colorCount == count($colors)) {
                $colorCount = 0;
            }
            $color[] = $colors[$colorCount];
        }

        $datasets = [];

        $d = new stdClass();
        $d->label = "Data 1";
        $d->backgroundColor = $color;
        $d->borderColor = $color;
        $d->data = $data1;
        $datasets[] = $d;

        return [
            "labels" => $labels,
            "datasets" => $datasets
        ];
    }
}
