<?php

/**
* Generated By GZeinNumerCodeGenerator
* www.github.com/gzeinnumer
* at 2022-12-17 13:01:10
* zip name 20221217130110_examples_v1_ywqvU8gSxW.zip
*/

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ExamplesV1Model extends Model
{
    use HasFactory;
    protected $table = 'examples_v1';
    protected $fillable = ['name'];
    protected $casts = [
        'created_at'  => 'datetime:Y-m-d H:i:s',
        'updated_at' => 'datetime:Y-m-d H:i:s',
    ];
}
